### PR TITLE
Fix/person lookup strip

### LINKED ISSUE #3393: Person lookup in 802.1x doesn't use stripped username
The person lookup that is triggered via 802.1x requests isn't checking if the source requires the username to be stripped.

That causes objects to not be found and the lookup to fail

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Perform stripping of the username if necessary when performing a person lookup

# Impacts
person lookup

# Issue
fixes #3393 

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* Fixed issue where username wasn't stripped during a person lookup (#3393)

### CODE REVIEW

File: lib/pf/lookup/person.pm [hunk 1]
```diff
@@ -35,7 +35,8 @@ Lookup informations on a person
 =cut
 
 sub lookup_person {
-    my ($pid, $source_id) = @_;
+    my ($pid, $source_id, $context) = @_;
+    use Data::Dumper; get_logger->info(Dumper(\@_));
```
Comment (fdurand) [inline lib/pf/lookup/person.pm]: debug maybe

Comment (julsemaan) [reply lib/pf/lookup/person.pm]: Removed it instead, it was just for my own debug

**Comment by julsemaan** [comment]
@fdurand 

Can you perform a last check + merge if its all good

I'd like to have this in the maintenance for a deployment I'm finalizing

**Review by fdurand — APPROVED** [review]
