### PR TITLE
fix pf-maint.pl while running behind a proxy

### LINKED ISSUE #3425: pf-maint.pl doesn't take *_proxy environment variables into account
As title says.

Steps to reproduce:
```console
# export http_proxy=http://1.1.1.1:3142
# export https_proxy=http://1.1.1.1:3142

# with use Data::Dumper; print Dumper($ua); at line 217
# ./pf-maint.pl 
[..]
'no_proxy' => [],
[..]
'proxy' => {
             'http' => 'http://1.1.1.1:3142',
             'https' => 'http://1.1.1.1:3142'
},
[..]

# yum info perl-libwww-perl.noarch 
[..]
Version     : 6.07
Release     : 4.2
[..]
From repo   : packetfence

```
I didn't see any traffic going to 1.1.1.1 on port 3142.

https://metacpan.org/pod/release/MSCHILLI/libwww-perl-6.07/lib/LWP/UserAgent.pm#Proxy-attributes

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Fix pf-maint.pl while its running behind a proxy

# Impacts
pf-maint.pl

# Issue
fixes #3425 

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* Fixed pf-maint.pl when its running behind a proxy (#3425 )

### CODE REVIEW

File: addons/pf-maint.pl [hunk 1]
```diff
@@ -277,7 +281,11 @@ sub get_url {
     my $request  = HTTP::Request->new( GET => $url ), my $response_body;
     my $ua       = LWP::UserAgent->new;
     $ua->show_progress(1);
-    $ua->env_proxy;
+    for my $proxy_var qw(http_proxy HTTP_PROXY) {
+        if($ENV{$proxy_var} && $ENV{$proxy_var} =~ /^http:\/\/(.+)/) {
```
Comment (fdurand) [inline addons/pf-maint.pl]: ^https ?!

Comment (julsemaan) [reply addons/pf-maint.pl]: ^Done ?!

File: addons/pf-maint.pl [hunk 2]
```diff
@@ -40,6 +40,7 @@ =head1 SYNOPSIS
 use IO::Handle;
 use Term::ReadKey;
 use IO::Interactive qw(is_interactive);
+use LWP::Protocol::connect;
```
Comment (fdurand) [inline addons/pf-maint.pl:43]: I don't see this package in the spec and in the debian dependencies, is it an extra package or does it come with another one ?

Comment (julsemaan) [reply addons/pf-maint.pl:43]: I think its the Fingerbank Perl lib that uses it so its installed on PF installs. Let me add it explicitly in the PF packaging in case we change the Fingerbank Perl packaging at some point

Comment (julsemaan) [reply addons/pf-maint.pl:43]: I added that package in our spec, its already in our repo so that should be golden
