### PR TITLE
Fix/851 omapi config is bogus

### LINKED ISSUE #851: OMAPI configuration is bogus
OMAPI configuration is wrongly built.
If enabled (ip2mac and/or mac2ip with OMAPI), the configuration will be built (only the omapi-port section) even if there's no key.
That actually means it will work but OMAPI will listen on 0.0.0.0 without being secured.

### PR DESCRIPTION
**Pull request by dwlfrth**
# Description

Do not configure OMAPI dhcpd side if no key is provided, even if the feature is enabled
# Impacts

iplog (ip2mac, mac2ip)
# Issue

fixes #851 
# Delete branch after merge

YES
# NEWS file entries
## Enhancements
- Now generates default OMAPI key on install time
## Bug Fixes
- Issue with dhcpd side OMAPI configuration being unsecure (#851)

### CODE REVIEW

**Comment by julsemaan** [comment]
I even think this is maintenance

**Comment by dwlfrth** [comment]
Please review

File: lib/pf/config.pm [hunk 1]
```diff
@@ -830,6 +830,23 @@ sub is_omapi_enabled {
...
+=cut
+
+sub is_omapi_configured {
+    return $FALSE unless $Config{'omapi'}{'host'} eq "localhost";
+
+    if ( ($Config{'omapi'}{'key_name'} && $Config{'omapi'}{'key_name'} ne '') && ($Config{'omapi'}{'key_base64'} && $Config{'omapi'}{'key_base64'} ne '') ) {
+        return $TRUE;
+    }
+
+    $logger->warn("OMAPI lookup is locally enabled but missing required configuration parameters 'key_name' and/or 'key_base64'");
```
Comment (fdurand) [inline lib/pf/config.pm:846]: A detail but key_base64will always be set

Comment (dwlfrth) [inline lib/pf/config.pm:846]: Yep but it is a pretty generic message... It is covering up if someone messes with the default one... and since it is the values we are checking I output them

File: addons/packages/packetfence.spec [hunk 2]
```diff
@@ -583,6 +583,10 @@ if [ ! -f /usr/local/pf/conf/ssl/server.crt ]; then
     cat /usr/local/pf/conf/ssl/server.crt /usr/local/pf/conf/ssl/server.key > /usr/local/pf/conf/ssl/server.pem
 fi
 
+# Create OMAPI key
+if [ ! -f /usr/local/pf/conf/pf_omapi_key ]; then
+    echo $(date) $HOSTNAME | base64 > /usr/local/pf/conf/pf_omapi_key
```
Comment (fdurand) [inline addons/packages/packetfence.spec]: Can we use something a little bit random.
Because if i want to crash the dhcpd service i just have do a brute force attack with a hash of a date and the hostname (it can be found).

Comment (fdurand) [inline addons/packages/packetfence.spec]: Something like that:
dd if=/dev/urandom bs=16 count=1 2>/dev/null | openssl enc -e -base64

Comment (extrafu) [inline addons/packages/packetfence.spec]: I would suggest something like that:

/usr/bin/openssl rand -base64 -out /usr/local/pf/conf/pf_omapi_key 32

Much more random, cleaner, faster, zammitier.

**Comment by dwlfrth** [comment]
Re-Review now that it has been Zammitified :muscle:
