### PR TITLE
Fix/7438 for maintenance patches and major/minor upgrades

### LINKED ISSUE #7438: Unable to upgrade to Debian 11.6 with PF 11.X and 12.X
**Describe the bug**
If you are running a PF version between 11.X and 12.X and you try to perform an OS upgrade to Debian 11.6, you will get following error related to MariaDB packages:

```
    Unpacking libmariadb-dev (1:10.5.18-0+deb11u1) over (1:10.5.15+maria~bullseye) ...
    dpkg: error processing archive /tmp/apt-dpkg-install-zAV6k2/08-libmariadb-dev_1%3a10.5.18-0+deb11u1_amd64.deb (--unpack):
     trying to overwrite '/usr/lib/x86_64-linux-gnu/pkgconfig/mariadb.pc', which is also in package libmariadbd-dev 1:10.5.15+maria~bullseye
```

Fresh installations performed on Debian will not have any issue.

**To Reproduce**
1. Try to perform an OS upgrade (Debian) on a PacketFence installation running 11.X or 12.X

**Expected behavior**
OS upgrade should not cause any disruption.

**Additional context**
There is a conflict between packages which are not necessary anymore but it's hard to overcome this issue through packaging because current `packetfence` packages depend of these packages.

As a workaround, users can perform PacketFence upgrades **without** performing OS upgrade during:
  * maintenance patches
  * major/minor upgrades through automation of upgrades

It means they will run PacketFence with MariaDB 10.5.15 until they perform an OS upgrade.

### PR DESCRIPTION
**Pull request by nqb**
# Description
Perform PacketFence and Debian upgrades on Debian in several steps:
- upgrade to PacketFence packages **only**. These packages doesn't depend anymore to libmariadb(d)-dev packages.
- remove libmariadb(d)-dev packages (using `apt autoremove`)
- upgrade Debian packages (including mariadb-* packages)

Expected state at end of a maintenance patch or at end of major/minor upgrade:
- latest PacketFence version of maintenance/11.X or maintenance/12.X version
- MariaDB packages at version 10.5.18
- libmariadb(d)-dev packages removed

# Impacts
- Maintenance patches
- Major/minor upgrades
- Fresh installations

# Code / PR Dependencies
- [x] Fixes on all maintenance/11.X and maintenance/12.X branches to remove libmariadbd-dev dependency (see https://github.com/inverse-inc/packetfence/commit/10cdce9dc27a8dd7b8e714bce1e060f8c7ac103b)
- [x] Rebuild documentation on website to provide instructions for maintenance patches

# Issue
fixes #7438 

# Delete branch after merge
YES

# Checklist
## Bug Fixes
If an issue exists on Github, please refer to it (name) along with it's number...
* Unable to upgrade to Debian 11.6 with PF 11.X and 12.X

### CODE REVIEW

**Comment by nqb** [comment]
One thing than need to be discuss is the removal of libmariadb(b)-dev packages from our 12.2 repositories.

I don't see a valid reason to keep them in our repositories: they didn't seem identical to official Debian packages

```
root@localhost:/usr/local/pf# apt-cache policy libmariadb-dev
libmariadb-dev:
  Installed: (none)
  Candidate: 1:10.5.18+maria~deb11
  Version table:
     1:10.5.18+maria~deb11 500
        500 http://inverse.ca/downloads/PacketFence/debian/12.2 bullseye/bullseye amd64 Packages
     1:10.5.18-0+deb11u1 500
        500 http://mirrors.linode.com/debian bullseye/main amd64 Packages

```

**Comment by JeGoi** [comment]
Ok tested on 11.2 (and 12.0) to 12.1 it is working but:
```
The text leading up to this was:
--------------------------
|diff --git a/docs/common/upgrade_packages.asciidoc b/docs/common/upgrade_packages.asciidoc
|index 751f0b9414b..b0cb70941e8 100644
|--- a/docs/common/upgrade_packages.asciidoc
|+++ b/docs/common/upgrade_packages.asciidoc
--------------------------
File to patch:
```
So perhaps backport with few modifications.

File: addons/full-upgrade/run-upgrade.sh [hunk 1]
```diff
@@ -76,6 +101,7 @@ function apt_upgrade_packetfence_package() {
   else
     DEBIAN_FRONTEND=noninteractive apt install -q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" packetfence -y
   fi
+  DEBIAN_FRONTEND=noninteractive apt autoremove -q -y
```
Comment (JeGoi) [inline addons/full-upgrade/run-upgrade.sh:104]: Maybe we should add a flag on this one.
To execute it only if everything is fine for exemple.

**Review by JeGoi — CHANGES_REQUESTED** [review]
~~Need to fix the debian out of scope and~~ perhaps add a flag to run it
(Not out of scope, truncated, my bad)

**Comment by nqb** [comment]
Thanks for your review @JeGoi !

> So perhaps backport with few modifications.

I will backport documentation changes only to maintenance/12.1 in order to rebuild website so it should not be a problem.

File: addons/full-upgrade/run-upgrade.sh (hunk 1 above)
Comment (nqb) [reply addons/full-upgrade/run-upgrade.sh:104]: IMHO, this is not necessary because the command itself already behave like this:
* useless packages to remove: they are removed
* no useless packages to remove: command do nothing

Comment (JeGoi) [reply addons/full-upgrade/run-upgrade.sh:104]: Ok then, it is fine with me.

**Review by JeGoi — APPROVED** [review]

**Review by fdurand — APPROVED** [review]
