### PR TITLE
Person lookup amelioration

### LINKED ISSUE #888: pf::person::lookup should always use stripped username
Will have to go through the code to make sure it's this way or LDAP queries will fail

### PR DESCRIPTION
**Pull request by julsemaan**
# Description

rework person lookup to strip username if needed
Also makes it more abstract so we can use it with other sources than LDAP
# Impacts

Authentication attributes lookup
# Issue

Fixes #888 
# Delete branch after merge

YES
# NEWS file entries
## New Features
- 
## Enhancements
- The person attributes lookup 
## Bug Fixes
- The person attributes lookup will now be made on the stripped username if needed (#888)

### CODE REVIEW

File: lib/pf/util.pm [hunk 1]
```diff
@@ -1011,6 +1012,25 @@ sub cert_has_expired {
...
 
+=item strip_username
+
+Will strip a username matching pattern user@realm or \\realm\user
+
+Returns ($user,$realm) if found or ($user) if not matching any realm pattern
+
+=cut
+
+sub strip_username {
```
Comment (fdurand) [inline lib/pf/util.pm:1061]: I think you will probably have to add $username =~ /(._)\%(._)/ to be close to radius default config

Comment (julsemaan) [inline lib/pf/util.pm:1061]: Done

File: lib/pf/util.pm [hunk 2]
```diff
@@ -1011,6 +1012,28 @@ sub cert_has_expired {
...
+    }
+    elsif($username =~ /(.*)\%(.*)/){
+        return ($1,$2);
+    }
+    elsif($username =~ /\\\\(.*)\\(.*)/) {
+        return ($2,$1);
+    }
+    return $username;
+}
+
```
Comment (louismunro) [inline lib/pf/util.pm:1083]: I will be an ass and say we should use named regexes here.
E.g. $suffix_rx = qr/(._)\@(._)/;

**Comment by louismunro** [comment]
Unit tests would be really nice.

File: lib/pf/util.pm (hunk 2 above)
Comment (dwlfrth) [inline lib/pf/util.pm:1083]: Don't think we need named regex but having a simple line comment describing which use case we are matching would be great.

Comment (louismunro) [inline lib/pf/util.pm:1083]: Well, I would argue that self documenting code is better than comments.
But that's me. I just ate a pigsnout sandwich for lunch, so...

File: lib/pf/Authentication/Source.pm [hunk 3]
```diff
@@ -217,8 +218,24 @@ sub match_condition {
 =cut
 
 sub search_attributes {
+    my ($self,$username) = @_;
     my $logger = Log::Log4perl->get_logger( __PACKAGE__ );
-    $logger->debug("Search_attributes is not supported on this source.");
+    my $realm;
+    ($username,$realm) = strip_username($username) if isenabled($self->{'stripped_user_name'});
```
Comment (dwlfrth) [inline lib/pf/Authentication/Source.pm:245]: :heart_eyes:

File: lib/pf/util.pm (hunk 2 above)
Comment (dwlfrth) [inline lib/pf/util.pm:1083]: I would agree with you if the regex was used more than once :) Since it is a pretty simple sub, almost self-described, I think just highlighting the use cases with comment would be enough.
Anyway.. one way or another... (https://www.youtube.com/watch?v=1VFuHj9_Tgw)
I think that comment would be necessary even in the case of a named regex.

**Comment by julsemaan** [comment]
Please re-review

File: t/util.t [hunk 4]
```diff
@@ -17,6 +17,22 @@ BEGIN {
     use_ok('pf::util::apache');
 }
 
+my @info = ("lzammit","turkeycorp");
```
Comment (dwlfrth) [inline t/util.t:20]: :heart_eyes:

**Comment by dwlfrth** [comment]
:rocket:
