### PR TITLE
Dispatcher rework

### LINKED ISSUE #1917: mod_evasive : cannot open shared object file
Saw on a CentOS 7 with latest updates.

`Description: failed to start (exit status 0) -- /usr/local/pf/bin/pfcmd: httpd: Syntax error on line 229 of /usr/local/pf/var/conf/httpd.conf.d/httpd.portal: Cannot load modules/mod_evasive20.so into server: /etc/httpd/modules/mod_evasive20.so: cannot open shared object file: No such file or directory`

The actual mod_evasive20.so is replaced by mod_evasive24.so. Tried to replace it in the httpd template file but another error showed up about the command used with mod_evasive.

Didn't push the debugging further.

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Dynamically chose http backend based on header and path in Haproxy and moved dispatcher logic in go reverse proxy.
 
# Impacts
Haproxy is always enabled even if there is no cluster config.
Better performances and use less memory for the portal.

# NEW Package(s) required
haproxy >= 1.6

# Issue
* #1301

# Delete branch after merge
YES

# NEWS file entries
## New Features
* New go reverse proxy to handle passthrough and redirection on the portal
* Refuse request on the portal if the answer is 501 and there is more than 20 request in 10s.
* Dynamic haproxy configuration

## Enhancements
* removed mod_qos and mod_evasive

## Bug Fixes
* fix #1917

# UPGRADE file entries
Mod_qos and mod_evasive are not yet supported in PacketFence.
If you want to limit the hit on the portal then you need to configure haproxy.

### CODE REVIEW

**Comment by julsemaan** [comment]
IMO we should be strict about not bringing in golang code without a fair amount of unit tests given the very alpha stage of all our golang APIs.

That will help assert that code does work even if it is refactored to adjust some go API

That should be valid for anything (including HTTP based services) as in golang its easy to create an http.Request from scratch and send it to ServeHTTP and validate the result

File: go/httpdispatcher/proxy.go [hunk 1]
```diff
@@ -0,0 +1,312 @@
...
+
+	for _, rgx := range p.detectionmechanisms {
+		if rgx.MatchString(e) {
+			return true
+		}
+	}
+	return false
+}
+
+// func (p *passthrough) checkParking(ctx context.Context, e string) bool {
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go]: Remove unless used

File: lib/pf/services/manager/httpd_portal.pm [hunk 2]
```diff
@@ -116,7 +99,8 @@ sub vhosts {
             uniq map {
                 defined $_->{'Tvip'} && $_->{'Tvip'} ne '' ? $_->{'Tvip'} : $_->{'Tip'}
             } @internal_nets, @portal_ints
-        ];
+        ] if $cluster_enabled;
```
Comment (julsemaan) [inline lib/pf/services/manager/httpd_portal.pm]: Wrapping this in a block with an if/else would be clearer in my opinion

File: go/caddy/httpdispatcher/httpdispatcher.go [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+
+type HttpDispatcherHandler struct {
+	Next  httpserver.Handler
+	proxy *httpdispatcher.Proxy
+}
+
+func (h HttpDispatcherHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) (int, error) {
+	ctx := r.Context()
+
+	defer func() {
```
Comment (julsemaan) [inline go/caddy/httpdispatcher/httpdispatcher.go:42]: This needs to use the paniccatcher once pfsso is merged

File: go/httpdispatcher/proxy.go [hunk 4]
```diff
@@ -0,0 +1,312 @@
...
+type passthrough struct {
+	proxypassthrough        []*regexp.Regexp
+	detectionmechanisms     []*regexp.Regexp
+	DetectionMecanismBypass bool
+	mutex                   sync.Mutex
+	WisprURL                *url.URL
+	PortalURL               *url.URL
+	URIException            *regexp.Regexp
+	SecureRedirect          bool
+	//	Cache                   *cache.Cache
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go]: Not needed

File: go/httpdispatcher/proxy.go [hunk 5]
```diff
@@ -0,0 +1,312 @@
...
+	fqdn.RawQuery = ""
+
+	//spew.Dump(fqdn.String())
+	//spew.Dump(r)
+	if host == "" {
+		w.WriteHeader(http.StatusBadGateway)
+		return
+	}
+
+	// if passThrough.checkParking(ctx, r.Header.Get("X-Forwarded-For")) {
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go]: Remove the parking code

File: go/httpdispatcher/proxy.go [hunk 6]
```diff
@@ -0,0 +1,312 @@
...
+
+	host := r.Host
+	var fqdn url.URL
+	fqdn.Scheme = r.Header.Get("X-Forwarded-Proto")
+	fqdn.Host = r.Host
+	fqdn.Path = r.RequestURI
+	fqdn.ForceQuery = false
+	fqdn.RawQuery = ""
+
+	//spew.Dump(fqdn.String())
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go]: Not needed

File: go/httpdispatcher/proxy.go [hunk 7]
```diff
@@ -0,0 +1,312 @@
...
+					<AccessLocation>CDATA[[isocc=,cc=,ac=,network=PacketFence,]]</AccessLocation>
+					<LocationName>CDATA[[PacketFence]]</LocationName>
+					<LoginURL>{{.WisprUrl.String}}</LoginURL>
+				</Redirect>
+			</WISPAccessGatewayParam>-->
+	</body>
+</html>`)
+		t.Execute(w, passThrough)
+
+		//spew.Dump(r)
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go]: Not needed

File: go/httpdispatcher/proxy.go [hunk 8]
```diff
@@ -0,0 +1,312 @@
...
+		//spew.Dump(r.Header.Get("X-Forwarded-Proto"))
+		log.LoggerWContext(ctx).Debug(fmt.Sprintln(host, "REDIRECT"))
+		return
+	}
+	if !p.checkEndpointList(ctx, host) {
+		log.LoggerWContext(ctx).Info(fmt.Sprintln(host, "FORBIDDEN"))
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go]: Could be useful to have the reason of the forbidden in the log line

File: go/httpdispatcher/proxy.go [hunk 9]
```diff
@@ -0,0 +1,312 @@
...
+	})
+	t := time.Now()
+
+	// Pass the context in the request
+	r = r.WithContext(ctx)
+	rp.ServeHTTP(w, r)
+	log.LoggerWContext(ctx).Info(fmt.Sprintln(host, time.Since(t)))
+}
+
+// Configure add default target in teh deny list
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go]: *the deny list

File: go/httpdispatcher/proxy.go [hunk 10]
```diff
@@ -0,0 +1,312 @@
...
+func (p *Proxy) Configure(ctx context.Context, port string) {
+	p.addToEndpointList(ctx, "localhost")
+	p.addToEndpointList(ctx, "127.0.0.1")
+}
+
+func (p *passthrough) readConfig(ctx context.Context) {
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go:160]: Will have to rework this to work with the pfconfig pool

File: go/httpdispatcher/proxy.go [hunk 11]
```diff
@@ -0,0 +1,312 @@
...
+
+	for _, v := range trapping.ProxyPassthroughs {
+		p.addFqdnToList(ctx, v)
+	}
+
+	for _, v := range portal.DetectionMecanismUrls {
+		p.addDetectionMechanismsToList(ctx, v)
+	}
+
+	//p.Cache = cache.New(3*time.Second, 1*time.Second)
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go]: You can remove this

File: go/httpdispatcher/proxy.go [hunk 12]
```diff
@@ -0,0 +1,312 @@
...
+	portalURL.Host = general.Hostname + "." + general.Domain
+	portalURL.Path = "/captive-portal"
+	portalURL.Scheme = scheme
+
+	wisprURL.Host = general.Hostname + "." + general.Domain
+	wisprURL.Path = "/wispr"
+	wisprURL.Scheme = scheme
+
+	p.WisprURL = &wisprURL
+	//general.Hostname + "." + general.Domain + "/wispr"
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go]: remove

File: go/httpdispatcher/proxy.go [hunk 13]
```diff
@@ -0,0 +1,312 @@
...
+	p.PortalURL = &portalURL
+	//general.Hostname + "." + general.Domain + "/captive-portal"
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go]: remvoe

File: go/httpdispatcher/proxy.go [hunk 14]
```diff
@@ -0,0 +1,312 @@
...
+
+}
+
+func newProxyPassthrough(ctx context.Context) *passthrough {
```
Comment (julsemaan) [inline go/httpdispatcher/proxy.go]: passthrough struct and functions aren't documented. Just a few lines should be enough

File: lib/pf/services/manager/haproxy.pm [hunk 15]
```diff
@@ -196,11 +242,6 @@ sub stop {
     return $result;
 }
 
-sub isManaged {
-    my ($self) = @_;
-    return $cluster_enabled;
```
Comment (julsemaan) [inline lib/pf/services/manager/haproxy.pm:201]: Won't it try to bind to 127.0.0.1:3306 in the current way its generated.

That could cause issues with standalone servers that have mysql binding to 0.0.0.0:3306

**Comment by extrafu** [comment]
Bump, what is the status of this PR?

**Comment by julsemaan** [comment]
waiting for the tests and adjustments on the comments

**Comment by julsemaan** [comment]
and a rebase as well i guess

File: lib/pf/services/manager/haproxy.pm (hunk 15 above)
Comment (fdurand) [reply lib/pf/services/manager/haproxy.pm:201]: Yes true, but now since we manage mariadb can we configure it to listen on the mgmt ip and keep haproxy listen on 127.0.0.1:3306 ?

**Comment by fdurand** [comment]
Bump

File: lib/pf/services/manager/haproxy.pm (hunk 15 above)
Comment (julsemaan) [reply lib/pf/services/manager/haproxy.pm:201]: that works

**Comment by julsemaan** [comment]
This is good.

Will merge this and open another PR for the pfconfig pool integration
