### PR TITLE
fix/auth-log-email

### LINKED ISSUE #2648: Auth log is not set to completed after email registration

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Auth log is not set to completed after email registration

Impacts
=======
Email registration workflow

Issue
=====
fixes #2648

NEWS file entries
=================

Bug Fixes
------------

* Auth log is not set to completed after email registration (#2648)

### CODE REVIEW

**Review by louismunro — APPROVED** [review]
Tested at a client site.
Does what it says.

**Comment by louismunro** [comment]
@dwlfrth can we merge (even if a bit late)?
This fixes an actual bug.
As opposed to, say CSP Headers...

File: html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm [hunk 1]
```diff
@@ -79,6 +80,9 @@ sub code : Path : Args(2) {
             get_logger->info("Extending duration to $unregdate");
             node_modify($node_mac, unregdate => $unregdate);
             pf::activation::set_status_verified($GUEST_ACTIVATION, $code);
+            my $sponsor_type = pf::Authentication::Source::EmailSource->getDefaultOfType;
```
Comment (julsemaan) [inline html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm]: We can't assume that anymore, we should find out what is the actual source that was used during the sponsor registration

**Review by julsemaan — CHANGES_REQUESTED** [review]

File: html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm (hunk 1 above)
Comment (julsemaan) [reply html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm]: s/sponsor/email/ also

**Comment by jrouzierinverse** [comment]
The real fix would require us to store the source in the activation record.
This would require a changes to the DB and other parts of the code.

We should wait for the next release for the proper fix.

Also I would prefer migrate this out of the controller and to a DynamicRouting::Module

**Comment by julsemaan** [comment]
@jrouzierinverse I partly agree with you for bringing this out of the controllers as one of the use cases that needs to be handled is the fact that the link for activation may be opened from another device than the one that is performing the registration. In that case, restoring the proper context in the DynamicRouting could be tricky as the state of the flow is stored in the session tied to the MAC address (and the device opening the link obviously doesn't share the MAC). That's why it was left in the controllers as the DynamicRouting assumes a single device is performing a chain of even which isn't the case for the email activation. I'm obviously opened to bringing it in DynamicRouting but that case will need to be properly handled.

And +1 for waiting for next release

**Comment by jrouzierinverse** [comment]
Should we wait till the next release for this one as the pull request needs to be adjusted.

**Comment by julsemaan** [comment]
@jrouzierinverse if you have time, IMO it would be good to adjust it since its a bug and not an enhancement.

**Comment by jrouzierinverse** [comment]
I will work on it after the dal is in

**Comment by jrouzierinverse** [comment]
Reworked please review

File: html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm [hunk 2]
```diff
@@ -217,6 +218,7 @@ sub doSponsorRegistration : Private {
         }
 
         pf::activation::set_status_verified($SPONSOR_ACTIVATION, $code);
+        pf::auth_log::record_completed_guest($activation_record->{source_id}, $node_mac, $pf::auth_log::COMPLETED);
```
Comment (julsemaan) [inline html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm]: Sponsor was already working to my knowledge since the record completed is made in the client portal directly

File: html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm [hunk 3]
```diff
@@ -179,8 +179,8 @@ sub do_sponsor_registration {
     }
 
     $info{'sponsor'} = $sponsor;
-
     $info{'subject'} = $self->app->i18n_format("%s: Guest access request", $Config{'general'}{'domain'});
+    $info{'source_id'} = $source->id;
```
Comment (julsemaan) [inline html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm:183]: No need for that I believe, for the reason outlined above

File: html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm (hunk 2 above)
Comment (jrouzierinverse) [reply html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm]: I will verify if the sponsor is working as you say.
Then I will just remove that dead code to avoid future confusion.

**Comment by julsemaan** [comment]
@jrouzierinverse 

This has pending comments + requires a rebase

**Comment by extrafu** [comment]
@jrouzierinverse Please rebase.

**Comment by jrouzierinverse** [comment]
Done

**Comment by extrafu** [comment]
@julsemaan Merge if alright.
