### PR TITLE
fix/4987

### LINKED ISSUE #4987: node_discovered is triggered when you create a node from API
When security event "Node discovered" is enable and you create a node, this security event is triggered.

**To Reproduce**
1. Enable "Node discovered" security event
2. Create a node
3. Check your mail box or mail queue

**Expected behavior**
Only trigger this security event when a node has been *discovered*, not created in web admin. By 
*discovered*, I mean data comes from DHCP or RADIUS request.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Only trigger the node discover security event in the context of radius and pfdhcplistener 

# Impacts
RADIUS / pfdhcplistener workflow

# Issue
fixes #4987

# Delete branch after merge
YES

# Checklist
- [ ] Document the feature
- [x ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Bug Fixes
* Only trigger the node discover security event in the context of radius and pfdhcplistener (#4987)

### CODE REVIEW

**Comment by nqb** [comment]
@jrouzierinverse, after a rebase, can I consider this PR ready for test ?

I will certainly need it soon for a customer deployment. 

Thanks.

**Comment by jrouzierinverse** [comment]
Yes

**Comment by jrouzierinverse** [comment]
Done

File: lib/pf/radius.pm [hunk 1]
```diff
@@ -392,6 +393,7 @@ sub accounting {
     my $timer = pf::StatsD::Timer->new();
     my ($self, $radius_request, $headers) = @_;
     my $logger = $self->logger;
+    local $pf::dal::node::TRIGGER_NODE_DISCOVERED = 1;
```
Comment (nqb) [inline lib/pf/radius.pm]: I don't think it's necessary here because sending an accounting request for a node which doesn't exist will not create the node in PacketFence DB.

**Review by nqb — CHANGES_REQUESTED** [review]
Except my note on accounting, it works as expected on RADIUS and DHCP.

No security event is triggered when creating node through web admin.

**Comment by nqb** [comment]
@jrouzierinverse, could you look at my comment ? Thanks.

File: lib/pf/radius.pm (hunk 1 above)
Comment (jrouzierinverse) [reply lib/pf/radius.pm]: You are right I removed it
