### PR TITLE
fix rsyslog/logrotate not catching certain logs

### LINKED ISSUE #3423: some processes logging to /var/log instead of /usr/local/pf/logs/
On a packetfence 8.1.0 system, I am seeing some processes going to /var/log/messages instead of the pf-specific log directory (and they are not being split to specific files).

In particular, the following processes are being found in /var/log/messages:

* api-frontend
* redis-server
* haproxy
* pfdns

I made the following changes to `packetfence.conf` under `rsyslog.d`:

```
[root@bds conf]# diff /etc/rsyslog.d/packetfence.conf.rpmorig /etc/rsyslog.d/packetfence.conf
163c163
< if $programname == "pfdns" then
---
> if $programname contains "pfdns" then
230a231,246
>
> # api-frontend.log
> if $programname == "api-frontend" then
>   -/usr/local/pf/logs/api-frontend.log
> & stop
>
> # redis_server.log
> if $programname == "redis-server" then
>   -/usr/local/pf/logs/redis_server.log
> & stop
>
> # haproxy_portal.log
> if $programname == "haproxy" and $msg contains "portal-http" then
>   -/usr/local/pf/logs/haproxy_portal.log
> & stop
>
```

but since the file is dynamically generated, Im not sure how to preserve these changes.

### PR DESCRIPTION
**Pull request by garci66**
# Description
Adds some missing filters to rsyslog.d config file that were causing messages to go to the system's syslog file (/var/log/messages) instead of the proper /user/local/pf/log/* files.

# Impacts
Logs for the following processes are now properly redirected
* api-frontend
* redis_server
* pfdns (some messages were going to /var/log/messages)
* haproxy_portal
Also api-frontend httpd log has been renamed to httpd.api-frontend.access to be caught by logrotate.

# Issue
fixes #3423 

# Delete branch after merge
YES

# NEWS file entries

## Bug Fixes
* issues with process logging to /var/log instead of local folder #3423 
* renames api-frontend.access log to be handled by logrotate

### CODE REVIEW

File: lib/pf/constants/syslog.pm [hunk 1]
```diff
@@ -124,7 +128,7 @@ our @SyslogInfo = (
     },
     {
         'name'       => 'pfdns.log',
-        'conditions' => [ '$programname == "pfdns"' ]
+        'conditions' => [ '$programname contains "pfdns"' ]sys
```
Comment (jrouzierinverse) [inline lib/pf/constants/syslog.pm]: This is a syntax error it would not compile in my tests

Comment (garci66) [reply lib/pf/constants/syslog.pm]: Sorry.. no idea where the 'sys' came from. Indeed, it should not be there. I did this edit on the online editor on github and I probably added it after testing on my system by accidentally typing on the console.

**Comment by garci66** [comment]
Sorry yes.. not sure where the 'sys' came from.  I updated the commit to remove it.  Had used the online editor and somehow I fat-fingered it after testing on my system
