### PR TITLE
Pfappserver - User\Realm encoding

### LINKED ISSUE #4531: v9-gui: display user with REALM in pid
When I try to display a user from Users menu with following pid: `MYDOMAIN\myname`, I got following error:

```json
message: "Unknown path /api/v1/user/MYDOMAIN/myname"
status: 404
```

Backslash doesn't seems to be handle correctly

### Steps to reproduce

```console
# pfperl-api get -M POST '/api/v1/users/' -c '{"pid":"MYDOMAIN\\myname","email":"foo@foo.ca"}' | jq
# pfperl-api get '/api/v1/user/MYDOMAIN\myname/' | jq .item.pid
"MYDOMAIN\\myname"

```
### Actual results

Impossible to display information for such users.

### Expected results

Display information for this users.

### PR DESCRIPTION
**Pull request by satkunas**
# Description
Adds encoding to API calls to allow backslash `\` in `pid` for `user\realm`.

# Impacts
Encodes /user API endpoints

# Issue
Fixes #4531 

# Delete branch after merge
YES

# Checklist
- [n/a] Document the feature
- [n/a] Add unit tests
- [n/a] Add acceptance tests (TestLink)

## Bug Fixes
* v9-gui: display user with REALM in pid (#4531)

### CODE REVIEW

**Comment by nqb** [comment]
@satkunas, it works for `MYDOMAIN\myname` but as reported by @julsemaan, trying to access `bar/bar` will fail.

To reproduce:
```
 pfperl-api get -M POST '/api/v1/users/' -c '{"pid":"bar/bar","email":"foo@foo.ca"}'
```

Let me know if you want to handle this case in another PR.

**Comment by satkunas** [comment]
Forward slash recoded to `~` in https://github.com/inverse-inc/packetfence/pull/4542/commits/6e3ca235c13d9d7de091c1e12fe9c8366f35da5f

Waiting on @jrouzierinverse implement decoding on backend for /users

**Comment by nqb** [comment]
It works as expected for me from the new GUI.

**Review by nqb — APPROVED** [review]

File: lib/pf/UnifiedApi/Controller/Crud.pm [hunk 1]
```diff
@@ -259,6 +266,7 @@ sub render_create {
     }
 
     my $id = $obj->{$self->primary_key};
+    $id =~ s#/#~#g;
     $self->res->headers->location($self->make_location_url($id));
     return $self->render(json => { id => $id , message => "'$id' created"}, status => $status);
```
Comment (julsemaan) [inline lib/pf/UnifiedApi/Controller/Crud.pm:272]: I believe that would display "'bob~bob' created" instead of "'bob/bob' created"

The location header should be adjusted but the ID in the message should be left untouched

Comment (nqb) [reply lib/pf/UnifiedApi/Controller/Crud.pm:272]: @julsemaan: you're right.

Comment (jrouzierinverse) [reply lib/pf/UnifiedApi/Controller/Crud.pm:272]: This has been resolved in 90b1c7cbec5ec659075c1f03f6907328367e7540
