### PR TITLE
Fix for 5106

### LINKED ISSUE #5106: Some DHCP info triggers use outdated Fingerbank data
**Describe the bug**
The triggers new_dhcp_info_from_managed_network and new_dhcp_info_from_production_network are triggered in lib/pf/dhcp/processor_v4.pm directly and not in fingerbank.pm. Also, they are triggered before the profiling happens. This means they use the data in the DB and not the most up to date info that will be computed in fingerbank.pm afterwards. We need to get this triggered after the Fingebank profiling.

### LINKED ISSUE #5196: pfpki: wrong display of buttons
**Describe the bug**
Buttons in Certificates menu are not correctly displayed.

**Screenshots**
See https://raw.githubusercontent.com/inverse-inc/packetfence/devel/docs/images/packetfence-pki-certificate_download.png

**Expected behavior**
Each button should be visible

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Fix issue 5106

# Impacts
Security events

# Issue
fixes #5106

# Delete branch after merge

YES | NO

# Checklist
- [ ] Document the feature
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries

## Bug Fixes
* Some DHCP info triggers use outdated Fingerbank data #5106

### CODE REVIEW

File: lib/pf/fingerbank.pm [hunk 1]
```diff
@@ -271,6 +271,14 @@ sub _trigger_new_dhcp_security_event {
 
     $apiclient->notify('trigger_security_event', %security_event_data);
 
+    my $cache = pf::CHI->new( namespace => 'trigger_violation' );
```
Comment (julsemaan) [inline lib/pf/fingerbank.pm]: Shouldn't the namespace be declared in CHI.pm also ?

**Comment by fdurand** [comment]
BUMP
