### PR TITLE
Dell N1500: use common regex to get MAC from LLDP

### LINKED ISSUE #5758: Dell N1500.pm: LLDP detection doesn't work
**Describe the bug**
When you enabled VoIP detection using Dell N1500 switch module, LLDP detection returns a wrong MAC in `@phones` array. I got: `0x:48:7a:5e:1a:fa` (wrong prefix and last two chars missing).

**To Reproduce**
1. Configure a Dell N1500 to do VoIP detection using LLDP
2. Plug a voice phone (not see by PacketFence previously)

=> Phone is not auto-registered.

**Expected behavior**
`@phones` array should contain a correct MAC and voice phone should be auto-registered.

**Additional context**
[Regex to catch MAC](https://github.com/inverse-inc/packetfence/blob/e1f6b4b1d332c9947ab8586525029a20c21cce9a/lib/pf/Switch/Dell/N1500.pm#L202) seems to be a bit different than for other vendors.

I got this behavior on a 6.6.0.15 firmware with Dell N1500 switch.

### PR DESCRIPTION
**Pull request by nqb**
# Description
Use common regex to get MAC from LLDP

Tested on 6.6.0.15

# Impacts
Dell N1500 switch module + dedicated unit test.

# Issue
fixes #5758 

# Delete branch after merge
YES

# NEWS file entries
## Bug Fixes
* Dell N1500.pm: LLDP detection doesn't work (#5758)

### CODE REVIEW

**Comment by nqb** [comment]
@BiasF told me that LLDP detection work for him using Dell N3000 or N1100-ON Switches with firmware in 6.6. So perhaps, MIB is not identical on all models.

**Comment by BiasF** [comment]
I will check it tomorrow if VOIP Autoregistration is working von N1100er switches.
All our phones are registered for a long time so maybe we doesn't noticed that it's not working.

On N3000 I already tested it (Unregistered phone, removed voice flag and restarted switchport)

**Just for information:** 
On N1500 you should upgrade your firmware, there is a Voice vlan related bug in that version which can cause that voice vlan traffic never reaches the voice device ;)

**Comment by nqb** [comment]
Thanks a lot @BiasF.

Regarding bug related to voice VLAN, do you speak about 6.6.0.15 version precisely ?

**Comment by BiasF** [comment]
Yes, it was fixed in 6.6.0.17 

You find the Full Release notes and the MIB Files for Dell Switches always inside of the Firmware Upgrade ZIP File.

**Comment by nqb** [comment]
Tested on v6.6.2.5 and it works.

Any news on your side @BiasF ?

File: lib/pf/Switch/Dell/N1500.pm [hunk 1]
```diff
@@ -199,9 +199,7 @@ sub getPhonesLLDPAtIfIndex {
                         && ($MACresult->{
                                 "$oid_lldpRemPortId.$cache_lldpRemTimeMark.$cache_lldpRemLocalPortNum.$cache_lldpRemIndex"
                             }
-                            =~ /([0-9A-Z]{2})\s?([0-9A-Z]{2})\s?([0-9A-Z]{2})\s?([0-9A-Z]{2})\s?([0-9A-Z]{2})\s?([0-9A-Z]{2}).*/i
-                        )
-                        )
+                            =~ /^(?:0x)?([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})(?::..)?$/i))
```
Comment (fdurand) [inline lib/pf/Switch/Dell/N1500.pm]: Just a detail this one will be better:

```
 =~ /^ (?:0x)?([0-9A-F]{2})([0-9A-F]{2})([0-9A-F]{2})([0-9A-F]{2})([0-9A-F]{2})([0-9A-F]{2})(?::..)?$/i))
```

Comment (nqb) [reply lib/pf/Switch/Dell/N1500.pm]: Hi @fdurand,

I replaced `A-Z` by `A-F` in regex.

I see a space at beginning of your regex, do you want me to add it or it's a typo ? If it's a typo, you can merge.
