### PR TITLE
Use several email addresses in alerting.emailaddr

### LINKED ISSUE #3578: alerting emailaddr : unexpected behavior with more than one address
The option `alerting.emailaddr` in `pf.conf` is designed for only one address but you can specify more than one, separated by comma without warnings. However, additional email addresses will never be notify.

In my opinion, we have two solutions:
1. disallow additional address in this field
1. permit additional address in this field

I'm not sure to have the big picture to choice between 1 and 2. What's your opinion ?

### PR DESCRIPTION
**Pull request by nqb**
# Description
Permit to use several email addresses in `alerting.emailaddr` (variable in `pf.conf`).
This variable is also used to generate `keepalived` configuration.

# Impacts
- `keepalived` config
- documentation
- `pfmailer()` function

# Issue
fixes #3578 

# Delete branch after merge
YES

# TODO

- [x] Correctly indent email addresses in `keepalived` generated config.

### CODE REVIEW

File: lib/pf/services/manager/keepalived.pm [hunk 1]
```diff
@@ -58,7 +58,8 @@ sub generateConfig {
 
     my %tags;
     $tags{'template'} = "$conf_dir/keepalived.conf";
-    $tags{'emailaddr'} = $Config{'alerting'}{'emailaddr'};
+    # split email addresses then rejoin them with line feed
+    $tags{'emailaddr'} = join("\n", split( /\s*,\s*/, $Config{'alerting'}{'emailaddr'}));
```
Comment (nqb) [inline lib/pf/services/manager/keepalived.pm]: Guys,

I need your help to have a well indented `keepalived` generated config. With current code, I get:
```
global_defs {
   notification_email {
     foo@example.com
bar@example.com
}
```

Comment (jrouzierinverse) [reply lib/pf/services/manager/keepalived.pm]: Try something like this
```perl
    $tags{'emailaddr'} = join("\n     ", split( /\s*,\s*/, $Config{'alerting'}{'emailaddr'}));
```

**Comment by nqb** [comment]
I modified `lib/pf/config/util.pm` due to a [MIME::Lite bug](https://rt.cpan.org/Public/Bug/Display.html?id=65606#txn-1028353).

**Review by julsemaan — APPROVED** [review]
LGTM

File: conf/documentation.conf [hunk 2]
```diff
@@ -632,8 +632,8 @@ EOT
 [alerting.emailaddr]
 type=text
 description=<<EOT
-Email address to which notifications of rogue DHCP servers, violations 
-with an action of "email", or any other PacketFence-related message 
+Comma-delimited list of email addresses to which notifications of rogue DHCP servers, violations
```
Comment (extrafu) [inline conf/documentation.conf:635]: Shouldn't we write "to which notifications of rogue DHCP servers ... should be sent, or or any other PacketFence-related message." ?

File: lib/pf/services/manager/keepalived.pm (hunk 1 above)
Comment (nqb) [reply lib/pf/services/manager/keepalived.pm]: @jrouzierinverse, @julsemaan: I will prefer using constants rather than a "blank space" and a piece of code like this:
```perl

# in pf/constants/{util,base}.pm ?
Readonly my $SPACE => q{ };
Readonly my $INDENT_SPACES => 4;

# in keepalived.pm
$tags{'emailaddr'} = join("\n" . ($SPACE x $INDENT_SPACES), split( /\s*,\s*/, $Config{'alerting'}{'emailaddr'}));
```
What's your opinion ?

File: conf/documentation.conf (hunk 2 above)
Comment (nqb) [reply conf/documentation.conf:635]: I kept the end of text in a separated line

File: lib/pf/services/manager/keepalived.pm (hunk 1 above)
Comment (jrouzierinverse) [reply lib/pf/services/manager/keepalived.pm]: Since this is very specific to keep alive at the moment just create a constant in lib/pf/services/manager/keepalived.pm.

However if you feel that they should be global constant put it in pf/constants.pm

**Comment by nqb** [comment]
You can review.

**Comment by julsemaan** [comment]
Still LGTM, unless @jrouzierinverse opposes to the wedding of this branch and devel, he shall speak now or forever hold his peace.
