### PR TITLE
Run pfconfig container on shell runner to generate material

### LINKED ISSUE #7206: ci: adjust build_artifacts_material_job job due to containerization
**Describe the bug**
Job build_artifacts_material_job needs to be refreshed for the next release because `pfconfig` is now containerized.

The file `material.html` can be generated on a PF dev machine without any problem.

### PR DESCRIPTION
**Pull request by nqb**
# Description
Generate material.html and upload it to our internal git repository.

# Impacts
Release

# Issue
fixes #7206 

# Delete branch after merge
YES

### CODE REVIEW

**Comment by nqb** [comment]
Pipeline in progress: https://gitlab.com/inverse-inc/packetfence/-/pipelines/699030760

File: ci/lib/build/generate-material.sh [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+	   -e GIT_REPO \
+	   -e CI_PIPELINE_ID \
+           -v ${PF_SRC_DIR}/conf:/usr/local/pf/conf \
+           -v ${PF_SRC_DIR}/addons/dev-helpers/bin:/usr/local/pf/addons/dev-helpers/bin \
+           -v ${PF_SRC_DIR}/ci/lib:/usr/local/pf/ci/lib \
+           -v ${PF_SRC_DIR}/config.mk:/usr/local/pf/config.mk \
+           -v ${PF_SRC_DIR}/Makefile:/usr/local/pf/Makefile \
+           ghcr.io/inverse-inc/packetfence/pfconfig:${IMAGE_TAG}
+    docker exec ${CONTAINER_NAME} /usr/bin/make material
+    docker exec ${CONTAINER_NAME} /usr/local/pf/ci/lib/release/publish-to-git.sh ${SRC_FILE} ${DST_FILE}
```
Comment (nqb) [inline ci/lib/build/generate-material.sh]: One thing I'm not 100% sure is the usage of `--detach` in that context.

According to my tests, shell script is moving directly to `make material` command after `docker run` while `pfconfig` container is starting. I suppose in some cases it could fail because `pfconfig` is not yet started. If you have better solution @julsemaan, let me know.

Comment (nqb) [reply ci/lib/build/generate-material.sh]: I added a `sleep` statement because I hit exactly that bug while building in CI.

**Comment by nqb** [comment]
Still having some issues due to .conf files necessary to run pfconfig.

I will finalize on Monday and ensure build is working as expected.

**Comment by nqb** [comment]
Successful pipeline: https://gitlab.com/inverse-inc/packetfence/-/jobs/3354820600

Changes were pushed to our private git repository. 

Ready for review and merge.
