### PR TITLE
Force mechanism LOGIN PLAIN

### LINKED ISSUE #7813: Unable to select SASL mechanism and timeout not honored
When configure SMTP settings in System Configuration > Alterting, it's not possible to select the SASL mechanism to use if SMTP authentication is required.

For example, if the server advertises "GSSAPI NTLM LOGIN", we'll incorrectly pick the first, GSSAPI which will lead to SMTP send failures.

We should force the user to pick between PLAIN and LOGIN, the only two we should support. PLAIN should be the default.

Also, the timeout isn't honored correctly when sending mails, especially in-between the TLS negotiation and the SMTP authentication. If it takes a couple of seconds, it'll fail independently of the timeout set in System Configuration > Alterting.

@fdurand please put the 2 lines of code you added at a customer to make it work, so anyone working on this will have some inspiration.

### PR DESCRIPTION
**Pull request by jrouzierinverse**
# Description
Force mechanism LOGIN PLAIN for SMTP.

# Issue
fixes #7813

# Delete branch after merge
YES

# Checklist
(REQUIRED) - [yes, no or n/a]
- [ ] Document the feature
- [ ] Add OpenAPI specification
- [ ] Add unit tests
- [ ] Add acceptance tests (TestLink)

# NEWS file entries
## Enhancements
* Force mechanism LOGIN PLAIN for SMTP. (#7813)

### CODE REVIEW

File: lib/pf/config/util.pm [hunk 1]
```diff
@@ -627,7 +628,15 @@ sub send_using_smtp_callback {
         and !$args{NoAuth} )
     {
         if ( $smtp->supports( 'AUTH', 500, ["Command unknown: 'AUTH'"] ) ) {
-            $smtp->auth( $args{AuthUser}, $args{AuthPass} )
+            my $sasl = Authen::SASL->new(
+              mechanism => 'LOGIN PLAIN',
```
Comment (extrafu) [inline lib/pf/config/util.pm]: I don't understand this.

Is the Perl library smart enough to prioritize LOGIN and then PLAIN? "LOGIN PLAIN" is not a single SASL mechanism, those are two different mechanisms and PLAIN should be prioritized, it's much more popular than LOGIN.

Comment (extrafu) [reply lib/pf/config/util.pm]: @jrouzierinverse Any updates on my comments?

Comment (jrouzierinverse) [reply lib/pf/config/util.pm]: By doing some source diving it seems to be the case.
It will attempt them in order removing which one failed and retry.
You can see how it used here.
https://metacpan.org/pod/Authen::SASL

Comment (extrafu) [reply lib/pf/config/util.pm]: Ok good, thanks for the explanation. Just flip LOGIN and PLAIN then, since PLAIN is a lot more popular.

Comment (extrafu) [reply lib/pf/config/util.pm]: What about the timeout? In the bug report, it's mentioned that is is not used and should be.

**Comment by satkunas** [comment]
@jrouzierinverse update timeout

@fdurand review after

**Comment by jrouzierinverse** [comment]
@fdurand please review
