### PR TITLE
fix/5267-pfacct-statsd

### LINKED ISSUE #5267: pfacct doesn't report metrics to dashboard
**Describe the bug**
I don't see any RADIUS accounting metrics in the RADIUS graph in the dashboard

**To Reproduce**
1. Send some accounting to pfacct
2. Look at dashboard

**Expected behavior**
RADIUS metrics should be displayed

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Adds stats to pfacct

Impacts
=======
Admin GUI

Issue
=====
fixes #5267

Delete branch after merge
=========================
NO

Checklist
=========
- [ ] Document the feature
- [x] Add unit tests
- [ ] Add acceptance tests (TestLink)

### CODE REVIEW

**Comment by extrafu** [comment]
Should we also show Netflow bandwidth statistics in the dashboard?

File: go/acct/radius.go [hunk 1]
```diff
@@ -41,9 +42,10 @@ func (h *PfAcct) hasher() hash.Hash64 {
 }
 
 func (h *PfAcct) HandleAccountingRequest(w radius.ResponseWriter, r *radius.Request) {
+	ctx := r.Context()
+	defer statsd.NewStatsDTiming(ctx).Send("pfacct.HandleAccountingRequest")
```
Comment (julsemaan) [inline go/acct/radius.go]: If you change the name of the timings here, you need to adjust the dashboard so that it uses the new names

File: go/acct/radius.go [hunk 2]
```diff
@@ -56,9 +58,11 @@ func (h *PfAcct) HandleAccountingRequest(w radius.ResponseWriter, r *radius.Requ
 }
 
 func (h *PfAcct) handleAccountingRequest(r *radius.Request, switchInfo *SwitchInfo) {
+	ctx := r.Context()
 	status := rfc2866.AcctStatusType_Get(r.Packet)
+	defer statsd.NewStatsDTiming(ctx).Send("pfacct.accounting." + status.String())
```
Comment (julsemaan) [inline go/acct/radius.go]: Same for the name adjustment here

**Review by julsemaan — CHANGES_REQUESTED** [review]

File: go/acct/radius.go (hunk 1 above)
Comment (fdurand) [reply go/acct/radius.go]: We still need the old graph since the radius-acct can still be used.

**Comment by fdurand** [comment]
I don't have anything in netdata when i sent some accounting.
Also we need to have the same logic than here:

```
https://github.com/inverse-inc/packetfence/blob/devel/go/dhcp/main.go#L137
```

**Comment by jrouzierinverse** [comment]
Ok will do

**Comment by jrouzierinverse** [comment]
Ready for testing

**Comment by fdurand** [comment]
have the graphs now , let me add in the dashboard
