### PR TITLE
Fixes #5351

### LINKED ISSUE #5351: web admin: unable to preview HTML files on a connection profile
**Describe the bug**
When you want to preview a HTML file of your connection profile, for example, `account.html`, you got `404 Site pfdeb9dev.lan:1443 is not served on this interface`
 
**To Reproduce**
1. Go in "Files" tab of any connection profile
2. Click on 'Preview'

**Expected behavior**
Should display preview of HTML file.

**Additional context**
If I try to edit `account.html` on `default` connection profile, my web browser try to reach https://pfdeb9dev.lan:1443/config/profile/default/preview/account.html

Similar to #5283

### PR DESCRIPTION
**Pull request by fdurand**
# Description
Fixes 5351

# Impacts
No

# Issue
fixes #5351

# Delete branch after merge
YES

### CODE REVIEW

File: conf/passthrough_admin.lua.tt.example [hunk 1]
```diff
@@ -41,6 +41,11 @@ core.register_action("admin", { "http-req" }, function(txn)
         local path = txn.sf:path():match("^/portal_preview(.*)")
         txn:set_var("req.path", path)
         txn:set_var("req.action","[% portal %]" .. "-portal")
+    elseif ( string.match(txn.sf:path(), '^/config/profile') ) then
+        --local params = parseurl(txn.sf:query())
```
Comment (julsemaan) [inline conf/passthrough_admin.lua.tt.example]: No need for this line right ?

Comment (fdurand) [reply conf/passthrough_admin.lua.tt.example]: Nope , just comment
