### PR TITLE
fix/readonly-pf-conf

### LINKED ISSUE #2464: read-only mode: Saving configuration parameters
Even by being in a read-only mode on a database point-of-view, it should be possible to save some configuration changes.

Some of them needs to be excluded from that logic since requires duplication in the database:
- switches
- roles
- violations

See #2458

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Description
===========
Allow saving configuration files in readonly mode except violation, switches, roles

Issue
=====
Fixes #2464

Delete branch after merge
=========================
NO

NEWS file entries
=================

Enhancements
------------
* Allow saving configuration files in readonly mode except violation, switches, role

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Please review

**Comment by julsemaan** [comment]
@lzammit will test

File: lib/pf/freeradius.pm [hunk 1]
```diff
@@ -161,7 +161,15 @@ Populates the radius_nas table with switches in switches.conf.
...
 sub freeradius_populate_nas_config {
     my $logger = get_logger();
-    return unless db_ping;
+    unless(db_ping()){
+        $logger->error("Can't connect to db");
+        return;
+    }
+
+    if (db_readonly_mode()) {
+        print STDERR "Cannot reload radius nas table when the database is in read only mode\n";
```
Comment (julsemaan) [inline lib/pf/freeradius.pm]: Lets just say 'the RADIUS clients table' instead of 'radius nas table' so that its «Zammit readable»

Comment (julsemaan) [reply lib/pf/freeradius.pm]: I'd also add a logging statement so that if we go back in the logs for support, we could know that their reload didn't work in case the person who did the reload just ignored the warning and is now complaining about things not working

File: lib/pf/nodecategory.pm [hunk 2]
```diff
@@ -106,6 +106,17 @@ It will simply do an upsert of all the roles in the configuration
...
     my ($config) = @_;
+    my $logger = get_logger;
+
+    unless(db_ping()){
+        $logger->error("Can't connect to db");
+        return;
+    }
+
+    if (db_readonly_mode()) {
+        print STDERR "Cannot reload roles when the database is in read only mode\n";
```
Comment (julsemaan) [inline lib/pf/nodecategory.pm]: same about logging statement

File: lib/pf/violation_config.pm [hunk 3]
```diff
@@ -42,6 +42,12 @@ sub loadViolationsIntoDb {
         $logger->error("Can't connect to db");
         return;
     }
+
+    if (db_readonly_mode()) {
+        print STDERR "Cannot reload violations when the database is in read only mode\n";
```
Comment (julsemaan) [inline lib/pf/violation_config.pm]: same about logging statement

File: lib/pf/freeradius.pm (hunk 1 above)
Comment (jrouzierinverse) [reply lib/pf/freeradius.pm]: OK

**Comment by jrouzierinverse** [comment]
Done
